# Site Settings
title: Alireza Amiri
url: 'http://alirezaamiri.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alireza Amiri
tagline: Research Assistant
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I have been always passionate about programming and software development. I've started my career as a web developer with the focus in PHP-based CMS and Frameworks. My biggest project in that era was in Pasargad Fartak Arian Co. There, an E-shop was implemented in Magento CE, a complex PHP e-commerce framework. I have learned a lot about design patterns and various architectures from Magento. <br>
Since two years ago, I have found another passion of mine, Python. I enjoyed using it in various student projects so far. From last year, I am using it as my professional choice as well. Working in GWDG, I am assigned to automate the deployment and execution of workloads in the cloud testbed, which is implemented by OpenStack. Here, I have gained experience in Python programming, shell programming, and cloud computing. Thanks to my current job, I have become familiar with DevOps tasks as well. I find CD and CI as amazing concepts which any software development team could benefit. Therefore, I have also tried to learn more about such topics. For instance, I have learned the fundamentals of Amazon Web Services, one the pioneers in offering cloud computing services.<br>
Besides, one of my personal interests is Game development which I try to grow in my leisure time and continue doing so as a hobby for now."

#sidebar links
email: alirezaamiri.ara@gmail.com
phone: 049 173 2860230
website: alirezaamiri.github.io #do not add http://
linkedin: alireza-amiri
github: alirezaamiri
twitter: 'alirezaamiriara'
#Update all the sections by editing the files inside _data folder.

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
