# Site Settings
title: Alireza Amiri
url: 'http://alirezaamiri.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alireza Amiri
tagline: Research Assistant
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'In Construction'

#sidebar links
email: alirezaamiri.ara@gmail.com
phone: 049 173 2860230
website: alirezaamiri.github.io #do not add http://
linkedin: alireza-amiri
github: alirezaamiri
twitter: 'alirezaamiriara'
#Update all the sections by editing the files inside _data folder.

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
